force-app/main/default/objects/Pricebook2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Method__c</fullName>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pricing_method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Option__c/Product_Option__c.object-meta.xml
<CustomObject>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO{000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Option__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Options</relationshipLabel>
    <relationshipName>Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Option__c/fields/Product_Option__c.field-meta.xml
<CustomField>
    <fullName>Product_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Option</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Options (Product Option)</relationshipLabel>
    <relationshipName>Product_Options1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Pricing_method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Currency</fullName>
    </customValue>
    <customValue>
        <fullName>Percent</fullName>
    </customValue>
    <masterLabel>Pricing method</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductSelector.cls
public inherited sharing class ProductSelector {
    
    public static List<PricebookEntry> getProductsAndOptions(Id productId, String country)
    {
        List<Id> listIds = new List<Id>();
        
        for(Product_Option__c po : getProductOptions(productId))
        {
            listIds.add(po.Product_Option__c);
        }
        
        return [SELECT Id,
                Name,
                UnitPrice,
                CurrencyIsoCode,
                Percent__c,
                Product2Id,
                Product2.Name,
                Product2.Pricing_Method__c,
                Pricebook2.Product__c,
                Pricebook2.Product__r.Name,
                Pricebook2.Country__c
                FROM PricebookEntry
                WHERE (Product2Id = :productId OR Product2Id IN :listIds)
                AND Pricebook2.Country__c = :country
                AND Pricebook2.Product__c = :productId];
    }
    
    public static List<Product_Option__c> getProductOptions(Id productId)
    {
        return [SELECT Product_Option__c FROM Product_Option__c WHERE Parent_Product__c = :productId];
    }
}