force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInfoController.cls
public with sharing class ProductInfoController {
    
    @AuraEnabled
	public static List<PricebookEntry> getProductInfo(Id caseId)
    {
        Case c = CaseSelector.getCaseById(caseId);

        if(c.ContactId != null && c.Contact.Product__c != null && !String.isBlank(c.Contact.Home_Country__c))
        {
            return ProductSelector.getProductsAndOptions(c.Contact.Product__c, c.Contact.Home_Country__c);
        }
        else
        {
            return null;
        }
    }
}