force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseSelectorTest.cls
@isTest
public class CaseSelectorTest {

    @isTest
    static void testGetCaseById()
    {
        Product2 p = TestDataFactory.createProducts(1)[0];
        insert p;
        
        Contact c = TestDataFactory.createContacts(1)[0];
        c.Home_Country__c = 'DE';
        c.Product__c = p.Id;
        insert c;
        
        Case ca = TestDataFactory.createCases(1)[0];
        ca.ContactId = c.Id;
        insert ca;
        
        Test.startTest();
        Case caseAux = CaseSelector.getCaseById(ca.Id);
        
        System.assertEquals(caseAux.ContactId, ca.ContactId);
        
        Test.stopTest();
    }
}