force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Home_Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductInfoControllerTest.cls
@isTest
public class ProductInfoControllerTest {
	@isTest
    static void testgetProductInfo()
    {
        Product2 p = TestDataFactory.createProducts(1)[0];
        insert p;
        
        Contact c = TestDataFactory.createContacts(1)[0];
        c.Home_Country__c = 'DE';
        c.Product__c = p.Id;
        insert c;
        
        PriceBook2 pb = TestDataFactory.createPricebooks(1, p, 'DE')[0];
        insert pb;
        
        PricebookEntry pbe = TestDataFactory.createPBEs(new List<Pricebook2>{pb}, new List<Product2>{p})[0];
        insert pbe;
        
        Case ca = TestDataFactory.createCases(1)[0];
        ca.ContactId = c.Id;
        insert ca;
        
        Test.startTest();
        List<PricebookEntry> listPBEs = ProductInfoController.getProductInfo(ca.Id);
        
        System.assertEquals(listPBEs.size(), 1);
        
        Test.stopTest();
    }
}