force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Send_email__c.field-meta.xml
<CustomField>
    <fullName>Send_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Date__c</fullName>
    <label>Survey Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Languages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>en</fullName>
        <default>true</default>
        <label>en</label>
    </customValue>
    <customValue>
        <fullName>de</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactSelector.cls
public inherited sharing class ContactSelector {
    
    public static List<Contact> getContactsToSurvey()
    {
        return [SELECT Id,
               FirstName,
               LastName,
               Language__c,
               Survey_date__c
               FROM Contact
               WHERE Survey_date__c < TODAY
               AND Email != null
               AND Send_email__c = false];
    }
}